language: php

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - composer install

script:
  - vendor/bin/simple-phpunit

jobs:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      script:
        - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.16.3/php-cs-fixer.phar
        - php php-cs-fixer.phar fix --dry-run --diff
        - vendor/bin/simple-phpunit

    - stage: release
      php: 7.1
      dist: precise
      install:
        - composer install --no-dev
        - wget https://github.com/humbug/box/releases/download/3.7.0/box.phar
      script:
        - mkdir -p build/
        - php box.phar compile
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: "get.insight.sensiolabs.com"
        skip_cleanup: true
        region: eu-west-1
        acl: public-read
        local_dir: build
        on:
          tags: true
